version: "3.4"
services:
  web:
    build: 
      context: front
      args: 
        PORT: 5000
        HOST: 127.0.0.1
    image: webapp:latest
    network_mode: host
  
  server:
    depends_on: 
      - redisdb
    build: 
      context: server
      args: 
        PORT: 8000
        HOST: 127.0.0.1
    image: server:latest
    network_mode: host
  
  server2:
    depends_on: 
      - redisdb
    image: server:latest
    network_mode: host
    command: flask run --port 8001
    
  redisdb:
    image: redis:latest
    network_mode: host
    expose: 
      - "6379"
