version: "3.4"
services:
  web:
    build: 
      context: front
    image: webapp:latest
    network_mode: host
    command: flask run --port 5000
  
  server:
    depends_on: 
      - redisdb
    build: 
      context: server
    image: server:latest
    network_mode: host
    command: flask run --port 8000
  
  server2:
    depends_on: 
      - redisdb
    image: server:latest
    network_mode: host
    command: flask run --port 8001
    
  redisdb:
    image: redis:latest
    network_mode: host
    expose: 
      - "6379"
